server:
  port: 1533

#mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.github.pig.admin.model.entity
  # 数据库相关配置
  global-config:
    #主键类型  0 or AUTO :"数据库ID自增",   1 or INPUT :"用户输入ID",     2 or ID_WORKER :"全局唯一ID (数字类型唯一ID)",    3 or UUID :"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
